
import Header from "@/components/Header";
import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <div className="flex flex-col h-screen">
         <Header/>
        <nav className="flex gap-4 justify-center bg-blue-900 p-4">
          <Link href="/" className="flex-1 text-center bg-blue-700 p-1.5 rounded-2xl text-gray-50">Home</Link>
          <Link href="/react-vs-nextjs-en" className="flex-1 text-center bg-blue-700 p-1.5 rounded-2xl text-gray-50">
          React Vs Next.js English</Link>
          <Link href="/react-vs-nextjs-fa" className="flex-1 text-center bg-blue-700 p-1.5 rounded-2xl text-gray-50">
          React Vs Next.js Farsi</Link>
          <Link href="/SSR-CSR" className="flex-1 text-center bg-blue-700 p-1.5 rounded-2xl text-gray-50">Cards</Link>
          <Link href="/shoping" className="flex-1 text-center bg-blue-700 p-1.5 rounded-2xl text-gray-50">Product</Link>
        </nav>
        <div className="flex flex-1">
          {children}
        </div>
       </div>
      </body>
    </html>
  );
}
